
language: objective-c
osx_image: xcode8

before_install:
  - export LANG=en_US.UTF-8
install:
  - gem install cocoapods -v 1.0.1 --no-document
  - gem install xcpretty --no-document

script:
  - rake travis
env:
  - PLATFORM=iOS
  - PLATFORM=OSX
